alias: null
batch_size: 32
dataloader_kwargs: null
decoder_hidden_layers: 0
decoder_hidden_size: 0
drop_last_loader: false
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 14
h_train: 1
hist_exog_list: null
inference_input_size: 71
inference_windows_batch_size: -1
input_size: 70
learning_rate: 0.0016259905900677177
loss: &id001 !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: &id002 !!python/name:torch.distributions.normal.Normal ''
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADYyMjg2MjY5MjhxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAA2MjI4NjI2
          OTI4cQFhLgMAAAAAAAAAAAAAP83MTD0zM3M/
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: Normal
  distribution_kwargs: {}
  domain_map: !!python/object/apply:builtins.getattr
  - *id001
  - _domain_map
  has_predicted: false
  horizon_weight: null
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 2
  param_names:
  - -loc
  - -scale
  return_params: false
  scale_decouple: &id004 !!python/name:neuralforecast.losses.pytorch.normal_scale_decouple ''
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
lstm_dropout: 0.007531953679840164
lstm_hidden_size: 64
lstm_n_layers: 2
max_steps: 1000
n_samples: 100
n_series: 1
num_lr_decays: 3
optimizer: null
optimizer_kwargs: null
random_seed: 7
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 14
training_data_availability_threshold: 0.0
trajectory_samples: 100
val_check_steps: 100
valid_batch_size: null
valid_loss: &id003 !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: *id002
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADYyMjg3NTkwNTZxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWAoAAAA2MjI4NzU5
          MDU2cQFhLgMAAAAAAAAAAAAAP83MTD0zM3M/
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: Normal
  distribution_kwargs: {}
  domain_map: !!python/object/apply:builtins.getattr
  - *id003
  - _domain_map
  has_predicted: false
  horizon_weight: null
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 2
  param_names:
  - -loc
  - -scale
  return_params: false
  scale_decouple: *id004
  training: true
windows_batch_size: 128
