alias: null
batch_size: 64
dataloader_kwargs: null
decoder_hidden_layers: 0
decoder_hidden_size: 0
drop_last_loader: false
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 10
h_train: 1
hist_exog_list: null
inference_input_size: 41
inference_windows_batch_size: -1
input_size: 40
learning_rate: 0.0012986282446045111
loss: &id001 !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: &id002 !!python/name:torch.distributions.normal.Normal ''
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADEzMzA4OTMxNTIwcQJYAwAAAG1wc3EDSwNOdHEEUS6AAl1xAFgLAAAAMTMzMDg5
          MzE1MjBxAWEuAwAAAAAAAAAAAAA/zcxMPTMzcz8=
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distr_mean: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCwAAADEzMzA5MTMzMDU2cQJYAwAAAG1wc3EDTWgBTnRxBFEugAJdcQBYCwAAADEzMzA5
      MTMzMDU2cQFhLmgBAAAAAAAAcuO6QC3lEUGZV/NAtWgbQaLL4ED2yBVBKhSPQIWdR0BAoONApjX7
      QMd3wEA/iT9BpVF0QWD3XEGpstJBcwgIQQJjMMDz5iRBEnnUQE0ffEFc0bNAvp/YQOkeBUHx22hB
      5J2IQYFmmUEPn95BvSaIQBhzz0COs35A2Lg0QKE9VT9Uqy1A+UMJQM1T+D+BnQRA4v0RQHuK8D+F
      vjE/J50ZP9SrGEDumhxASJoeQC9IH0AN7R9AHC0hQFntIkDusSRACh0mQD9HJ0A+JwtA7IiCP3Sa
      rz/itbw/o1lkQLdgkkBvR4BAEntGQNtwBkCzpxJAlBp8PRaFij3Vk5g9oimmPTW/sz0NxL49x0O/
      PdsgtD1siqc9nIWcPcAuEz+Phxw/NEBMP7EEBDug23I+MAxsPkpjyD7JzlU/WKeePvZXpT07qKVA
      LhSmQEpFpkAhaaZAfpqmQDjXpkA+E6dAsEGnQA9ep0B4cadAilFePyghRj+Q8hxAXHwnQFoEKUCc
      ewhAOVIYQH/kKT8AzHs/wm8MQC8Ysb7sup4/HBp6PxTCuj+OkQRAqjARQKyxFkCRjQ1AemtYvxJa
      Oz/Cs+g/0p4jQAgcZUBhwD1AnkxxQI3vJEAl0eQ+91iCP3VjgT+JytA/wX5+PmQzjT42+I0++LfI
      Pjc6/j4U7r0+ROTDPuBRhz47zaY+KsGaPrR5GT4u08s9/xKePXo4vD2frK898FSCPSrF8D1U9Ck+
      eWY4Pvd8OD5sDmFATXuQQF74tUAxTvhAsYgHQTR8HEEMtNpASmStQLdpHkH2HSVBrjg6P1HGSj8n
      Wys/n+hnvuXkjj7SN8g+LO8iPw+yez9oYsE+zqQHPjHLiz/bS68/yPJTP/eIzj4DNxc/ZfYtP+f6
      8T6xrR4/fMxLPyoDLD+BVvk9xQiAPXl0TD74gPo+H4AbP3iF4D7l7T4+60LhPQA7oz3RqOI9+2UH
      QUxYH0Fx3lFBblOBQQnQjkEEZItBFbJ4QasrW0FiXEtBj8k1QXTZgT0RNus9zQSBPg9qtz7KMIU+
      4Ls/PqRWFD5wZLq8qQXlvCIo+T0on64/bXXqP9RpSD/ZFhQ/KDF3Px24Ez81siU/wVisPwGxoj/U
      aMY/qVQEPtIHfj1zjp08fIgbvM9tCD2WEYk8EWYPPT/+hT09xrs9C6IqPdfxjj6zFrY+D5xBPz/g
      xD/nMLQ/y5frPiU9vj59ggU/JyF2Pn7gEj+ATK4/dNSLP6ctPT84Gww/2nRUPxZ+Iz/MieA+gsYK
      P6KbTT//pks/MrOdQKwoikDSQYRA7Z9hQMAGM0DY6l9A3GugQJ9yyUDtMOdAGJPxQJQafD0WhYo9
      1ZOYPaIppj01v7M9DcS+PcdDvz3bILQ9bIqnPZyFnD1SlD68ACZbPYxxCz7XUSo+YrNDPqoC7T0+
      0hU+Z9VMPfa7+bxsm8080bUhPg9aDT4Siw8+KuDvPbsUbT3tq7A9gcNIPc5U1TyzZ4o9qNzOPXz5
      HD+QUh0/fnYjP8+yyT6n1kk/Ru5dP184lT8Xq3c/fiyZP/M3jT9cHfA9btwdPXHf4Ly8Q409YTnq
      PFetTj1rg+o9AwI3PuNNrz3PYOk7lBp8PRaFij3Vk5g9oimmPTW/sz0NxL49x0O/PdsgtD1siqc9
      nIWcPZQafD0WhYo91ZOYPaIppj01v7M9DcS+PcdDvz3bILQ9bIqnPZyFnD24HLA9lQEqPcXukzuG
      CWK7TZCdPMZqPz1WCuE9PmP0PeR/oT3H+lA9p6xQPj3cdT7QPIc+TuhfPpSygz7Gd5o+xn9kPtB+
      bD4A5C0+UKMpPpQafD0WhYo91ZOYPaIppj01v7M9DcS+PcdDvz3bILQ9bIqnPZyFnD0xDoE8IsJ/
      PObA6j2xpuM904cLPQLnR7xUEJY8GrAiPYJN/D0w7RQ+
  - 0
  - !!python/tuple
    - 36
    - 10
    - 1
  - !!python/tuple
    - 10
    - 1
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  distribution: Normal
  distribution_kwargs: {}
  domain_map: !!python/object/apply:builtins.getattr
  - *id001
  - _domain_map
  has_predicted: false
  horizon_weight: null
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 2
  param_names:
  - -loc
  - -scale
  return_params: false
  scale_decouple: &id004 !!python/name:neuralforecast.losses.pytorch.normal_scale_decouple ''
  training: false
lr_scheduler: null
lr_scheduler_kwargs: null
lstm_dropout: 0.3598269083052652
lstm_hidden_size: 256
lstm_n_layers: 3
max_steps: 2000
n_samples: 100
n_series: 1
num_lr_decays: 3
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: minmax1
start_padding_enabled: false
stat_exog_list: null
step_size: 1
training_data_availability_threshold: 0.0
trajectory_samples: 100
val_check_steps: 100
valid_batch_size: null
valid_loss: &id003 !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: *id002
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCwAAADEzMzA5MjI5MTY4cQJYAwAAAGNwdXEDSwNOdHEEUS6AAl1xAFgLAAAAMTMzMDky
          MjkxNjhxAWEuAwAAAAAAAAAAAAA/zcxMPTMzcz8=
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: Normal
  distribution_kwargs: {}
  domain_map: !!python/object/apply:builtins.getattr
  - *id003
  - _domain_map
  has_predicted: false
  horizon_weight: null
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 2
  param_names:
  - -loc
  - -scale
  return_params: false
  scale_decouple: *id004
  training: true
windows_batch_size: 1024
